### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by httpbob** [uncss/uncss#363]
Hello,

I have installed uncss this way:
`sudo npm install -g uncss`

then I tried the following command:

> uncss https://getbootstrap.com/docs/3.3/examples/jumbotron/ > stylesheet.css

```
/usr/local/lib/node_modules/uncss/src/uncss.js:64
function getCSS([files, options, pages, stylesheets]) {
                ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/uncss/bin/uncss:8:19
    at Object.<anonymous> (/usr/local/lib/node_modules/uncss/bin/uncss:98:2)
    at Module._compile (module.js:410:26)

```

Find below my versions of npm + nodejs
`npm -v`
`3.5.2`

`nodejs -v`
`v4.2.6`

Can you please help me with that issue ?

**Comment by RyanZim** [comment]
You need to be using Node version 6 or higher for uncss to work.
