### ISSUE TITLE
gulp post-uncss not work

### ISSUE THREAD

**Issue by EugenGedroyc** [uncss/uncss#378]
In the console have error:
```
`An error was encountered in postcss-uncss; do you have uncss installed as a dependency?
[SyntaxError: Unexpected token []
[17:12:42] Using gulpfile C:\work\325\layout\gulpfile.js
[17:12:42] Starting 'postcssZavhoz'...
[17:12:42] 'postcssZavhoz' errored after 238 μs
[17:12:42] TypeError: postUncss is not a function
    at Gulp.<anonymous> (C:\work\325\layout\gulpfile.js:105:9)
    at module.exports (C:\work\325\layout\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\work\325\layout\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\work\325\layout\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\work\325\layout\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Евгений\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3`
```

In the gulpfile.js: 
```
`var postcss = require('gulp-postcss');
    var postUncss = require('postcss-uncss');
    gulp.task('postcssZavhoz', function () {
        var plugins = [
            postUncss({
              html: [
                'index.html'
                ],
              ignore: ['.js']
            })
        ];
        return gulp.src(cssZavhoz)
            .pipe(postcss(plugins))
            .pipe(gulp.dest(function (file) {
                return file.base;
        }));
    });`
```
modules has been installed, and packaje.json has :
"postcss-uncss": "^0.16.1",
"uncss": "^0.16.2"

Why "An error was encountered in postcss-uncss; do you have uncss installed as a dependency?" and "postUncss is not a function" ?

**Comment by RyanZim** [comment]
What Node.js version? Edit your gulpfile:
```patch
  var postUncss = require('postcss-uncss');
+ console.log(postUncss);
      gulp.task('postcssZavhoz', function () {
```
and post the output here.

**Comment by EugenGedroyc** [comment]
output: `{}`
nodeJs v4.4.3

**Comment by RyanZim** [comment]
Try replacing `var postUncss = require('postcss-uncss');` with `var postUncss = require('uncss').postcssPlugin;`

**Comment by EugenGedroyc** [comment]
if  i add any variable with `require('uncss')` or `require('uncss').postcssPlugin;`  console output for any gulp-task:
`C:\work\325\layout\node_modules\uncss\src\uncss.js:64
function getCSS([files, options, pages, stylesheets]) {
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\work\325\layout\gulpfile.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by RyanZim** [comment]
Just realized the problem here, you have to be using Node v6 or higher; sorry for not thinking of this earlier.
