### ISSUE TITLE
UnCSS cannot fetch JS files with relative paths

### ISSUE THREAD

**Issue by amyspark** [uncss/uncss#394]
I've replaced all remote JS with local copies + SRI:
```html
<script type="text/javascript" external="true" src="/assets/js/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
<script type="text/javascript" external="true" src="/assets/js/bootstrap.bundle.min.js" integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=" crossorigin="anonymous"></script>
```
I'm using UnCSS through PostCSS, and it fails to retrieve these. It seems like it doesn't remember the document root:
```
Error: Could not load script: "file:///assets/js/bootstrap.bundle.min.js"
    at /Users/amalia/Desktop/blog_v2/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:44:23
    at Object.check (/Users/amalia/Desktop/blog_v2/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at ReadStream.<anonymous> (/Users/amalia/Desktop/blog_v2/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12)
    at ReadStream.wrappedEnqueued (/Users/amalia/Desktop/blog_v2/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.emit (events.js:188:13)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at /Users/amalia/Desktop/blog_v2/node_modules/graceful-fs/graceful-fs.js:207:14
    at /Users/amalia/Desktop/blog_v2/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.args [as oncomplete] (fs.js:147:20) { [Error: ENOENT: no such file or directory, open '/assets/js/bootstrap.bundle.min.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/assets/js/bootstrap.bundle.min.js' }
```

**Comment by pavelstoev-lci** [comment]
Same problem still exists, using postcss-uncss. The only way I was able to make it work is to 1) set the htmlroot as described before and 2) change the relative path to rooted paths (e.g. ./styles/ to /styles) which is invalid HTML unless served from a web server.
