### ISSUE TITLE
Error with some missing dependency on NodeJS 10.15? 

### ISSUE THREAD

**Issue by slim16165** [uncss/uncss#395]
```
C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS>uncss http://www.ilcomuneinforma.it/viaggi/ > stylesheet.css
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\living\generated\HTMLCanvasElement.js:50:45)
    at http://www.ilcomuneinforma.it/viaggi/:40:931
    at http://www.ilcomuneinforma.it/viaggi/:40:1741
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at processJavaScript (C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:190:10)
    at HTMLScriptElementImpl._innerEval (C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:122:5)
    at C:\Users\Utente\AppData\Roaming\npm\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22 undefined
```

**Comment by slim16165** [comment]
Is it possible to force UnCSS to ignore canvas?
ᐧ

Il giorno gio 24 gen 2019 alle ore 20:03 Ryan Zimmerman <
notifications@github.com> ha scritto:

**Comment by RyanZim** [comment]
You can set uncss to use a special useragent, and put useragent exceptions in your code.
