### ISSUE TITLE
UnCSS 0.17 is broken because of JSDOM

### ISSUE THREAD

**Issue by amyspark** [uncss/uncss#404]
Hey @giakki,

UnCSS 0.17 is currently broken in my Gulp pipeline. This is the error message:

```
[18:46:37] TypeError in plugin "gulp-postcss"
Message:
    Cannot set property 'resources' of undefined
Details:
    fileName: /Users/amalia/Desktop/blog/_sass/amyspark.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

Stack:
TypeError: Cannot set property 'resources' of undefined
    at Object.fromSource (/Users/amalia/Desktop/blog/node_modules/uncss/src/jsdom.js:61:26)
    at Promise.all.files.map (/Users/amalia/Desktop/blog/node_modules/uncss/src/uncss.js:36:50)
    at Array.map (<anonymous>)
    at getHTML (/Users/amalia/Desktop/blog/node_modules/uncss/src/uncss.js:36:30)
    at process (/Users/amalia/Desktop/blog/node_modules/uncss/src/uncss.js:221:12)
    at /Users/amalia/Desktop/blog/node_modules/uncss/src/uncss.js:254:16
    at LazyResult.run (/Users/amalia/Desktop/blog/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/amalia/Desktop/blog/node_modules/postcss/lib/lazy-result.js:208:26)
    at /Users/amalia/Desktop/blog/node_modules/postcss/lib/lazy-result.js:250:14
    at new Promise (<anonymous>)
[18:46:37] 'prod' errored after 5.08 s
```

I'm using UnCSS from within PostCSS as follows:
```es6
gulp.task('sass:prod', () => {
  return gulp.src('_sass/amyspark.scss')
    .pipe(sass({
      includePaths: ['_sass/', 'node_modules'],
      outputStyle: 'expanded',
      implementation: require('node-sass'),
      precision: 10
    }))
    .pipe(postcss([
      require('uncss').postcssPlugin({
        html: ['public/**/*.html'],
        htmlroot: 'public/'
      }),
      require('autoprefixer')
    ]))
    .pipe(gulp.dest('public/assets'))
})
```
Looking on the releases page, I think this is related to https://github.com/uncss/uncss/commit/93e8eb931589e0bd0242a9bc86c1ac4a42a8dba8.

**Comment by giakki** [comment]
You're right, it looks like I forgot to map the htmlroot option in the postcss plugin.
While investigating this I also found some inconsistencies in jsdom's ResourceLoader, I might need to look into this a bit further.

The workaround for 0.17.0 is setting the `jsdom` option to an empty object:

```js
  require('uncss').postcssPlugin({
        html: ['public/**/*.html'],
        htmlroot: 'public/',
        jsdom: {},
      }),
```
which should work unless you run into the other issue.
