### ISSUE TITLE
Uncss error: Cannot read property 'getCookieStringSync' of undefined

### ISSUE THREAD

**Issue by keirwilliams** [uncss/uncss#408]
```
(node:57104) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCookieStringSync' of undefined
    at RequestJar.getCookieString (/usr/local/lib/node_modules/uncss/node_modules/request/lib/cookies.js:29:20)
    at Request.jar (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:1455:33)
    at Request.init (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:301:8)
    at Request.RP$initInterceptor [as init] (/usr/local/lib/node_modules/uncss/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/uncss/node_modules/request/index.js:53:10)
    at HtmlrootResourceLoader.fetch (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:95:16)
    at HtmlrootResourceLoader.fetch (/usr/local/lib/node_modules/uncss/src/jsdom.js:32:22)
    at PerDocumentResourceLoader.fetch (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at HTMLScriptElementImpl._fetchExternalScript (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:93:30)
(node:57104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not sure if this is my doing or not.

**Comment by stalsma-palmetto** [comment]
I'm seeing the same issue w node v10.16.

`uncss -H build/ -C build/styles/ build/**/*.html -o build/styles/stylePurged/style.min.css`

`
(node:64918) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCookieStringSync' of undefined
    at RequestJar.getCookieString (/usr/local/lib/node_modules/uncss/node_modules/request/lib/cookies.js:29:20)
    at Request.jar (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:1455:33)
    at Request.init (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:301:8)
    at Request.RP$initInterceptor [as init] (/usr/local/lib/node_modules/uncss/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/uncss/node_modules/request/index.js:53:10)
    at HtmlrootResourceLoader.fetch (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:95:16)
    at HtmlrootResourceLoader.fetch (/usr/local/lib/node_modules/uncss/src/jsdom.js:32:22)
    at PerDocumentResourceLoader.fetch (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at HTMLScriptElementImpl._fetchExternalScript (/usr/local/lib/node_modules/uncss/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:93:30)
(node:64918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by Reggino** [comment]
node 8 has the same isssue
