### ISSUE TITLE
References with query string

### ISSUE THREAD

**Issue by Lladnar2** [uncss/uncss#414]
Any reference that includes a query string does not work as uncss, or support modules, can not find the file.  Using

link href="../styles/main.min.css?cb=9766903" rel="stylesheet" media="all"

uncss will look for the file called main.min.css?cb=9766903.

Error:
Error: Could not load script: "file:///E:/websites/__t/prod/scripts/main.min.js?cb=9766903"
    at onErrorWrapped (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at request.then.catch.err (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14) { [Error: ENOENT: no such file or directory, open 'E:\websites\__t\prod\scripts\main.min.js?cb=9766903']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\websites\\__t\\prod\\scripts\\main.min.js?cb=9766903' }
Error: Could not load script: "file:///E:/websites/__t/prod/scripts/main.min.js?cb=9766903"
    at onErrorWrapped (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at request.then.catch.err (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14) { Error: request canceled by user
    at Promise.promise.abort (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (E:\websites\__t\node_modules\uncss\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at pages.forEach (E:\websites\__t\node_modules\uncss\src\uncss.js:223:49)
    at Array.forEach (<anonymous>)
    at cleanup (E:\websites\__t\node_modules\uncss\src\uncss.js:223:19) isAbortError: true }

Screenshot of code:
![uncss query string issue 2019-09-06 16_07_47](https://user-images.githubusercontent.com/30782888/64465326-ee310900-d0c0-11e9-8c6b-da81e110ccad.png)

**Comment by RyanZim** [comment]
PR welcome to fix.
