### ISSUE TITLE
TypeError: Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by illycz** [uncss/uncss#425]
I'm using AOS library, where in the code is: `var e=document.querySelectorAll("[data-aos]");`.
In HTML I have element with `data-aos` attribute, but in console I get: `[TypeError: Cannot read property 'querySelectorAll' of undefined]`

Any suggestions?

Thanks

**Comment by illycz** [comment]
Here is full log:

```
Error: Uncaught [TypeError: Cannot read property 'querySelectorAll' of undefined]
    at reportException (/Users/illy/Sites/_Templates/ceskoplatikartou/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at notifyMutationObservers (/Users/illy/Sites/_Templates/ceskoplatikartou/node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:166:11)
    at Promise.resolve.then (/Users/illy/Sites/_Templates/ceskoplatikartou/node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5) TypeError: Cannot read property 'querySelectorAll' of undefined
    at ne (file:///Users/illy/Sites/_Templates/ceskoplatikartou/public/assets/javascripts/app-72f79bbe0ac08933b804.js:1:12280)
    at ce (file:///Users/illy/Sites/_Templates/ceskoplatikartou/public/assets/javascripts/app-72f79bbe0ac08933b804.js:1:12915)
    at file:///Users/illy/Sites/_Templates/ceskoplatikartou/public/assets/javascripts/app-72f79bbe0ac08933b804.js:1:2903
    at Array.forEach (<anonymous>)
    at MutationObserverImpl.a [as _callback] (file:///Users/illy/Sites/_Templates/ceskoplatikartou/public/assets/javascripts/app-72f79bbe0ac08933b804.js:1:2615)
    at notifyMutationObservers (/Users/illy/Sites/_Templates/ceskoplatikartou/node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:158:14)
    at Promise.resolve.then (/Users/illy/Sites/_Templates/ceskoplatikartou/node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5)
./public/assets/stylesheets/app-212828ef47.css has been saved!
```
