### ISSUE TITLE
Error: Could not load script: "file:/// - fails in [17.2 and 17.3] - 17.1 is ok.

### ISSUE THREAD

**Issue by Zokor** [uncss/uncss#430]
Hi,

Started having this issue in version 17.2 and 17.3.

If i revert to 17.1 is fine.

My package.json is:

    "autoprefixer": "9.7.6",
    "browser-sync": "2.26.7",
    "cssnano": "4.1.10",
    "gulp": "4.0.2",
    "gulp-changed": "4.0.2",
    "gulp-concat": "2.6.1",
    "gulp-htmlmin": "5.0.1",
    "gulp-imagemin": "7.1.0",
    "gulp-order": "1.2.0",
    "gulp-plumber": "1.2.1",
    "gulp-postcss": "8.0.0",
    "gulp-rename": "2.0.0",
    "gulp-sass": "4.0.2",
    "gulp-sourcemaps": "2.6.5",
    "gulp-uglify": "3.0.2",
    "imagemin-gifsicle": "7.0.0",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-pngquant": "8.0.0",
    "imagemin-svgo": "7.1.0",
    "node-sass": "4.13.1",
    "postcss-import": "12.0.1",
    "postcss-uncss": "0.17.0",
    "precss": "4.0.0",
    "uncss": "0.17.1"

Home it helps debugging.

Cheers

**Comment by emmercm** [comment]
I might have a similar problem, unsure from the description, but given some HTML with some local JavaScript:

```html
<script src="static/script.js"></script>
```

starting in v0.17.2 I get something similar to:

```
(node:4059) ExperimentalWarning: The fs.promises API is experimental
Error: Could not load script: "static/script.js"
    at onErrorWrapped (.../node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (.../node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
    at request.then.catch.err (.../node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:124:14)
```

but the callback isn't called with an error.

**Comment by divji** [comment]
+ same problem
